### PR TITLE
Remove intent, use Event constant

### LINKED ISSUE #12: Remove non-required Guilds intent
I'm just going to post this here because *technically* in the example bot the `Guilds` intent isn't even required. This intent just sends events related to guilds but the example code doesn't even require that at the moment. You can find a list of intents + the events they can receive on the official Discord Documentation that you can find here: https://discord.com/developers/docs/topics/gateway#gateway-intents

Though I currently assume the intent is there as an example that you *should* put them there.

image

### PR DESCRIPTION
**Pull request by dipamsen**
Fixes #12

### CODE REVIEW

**Review by supercrafter100 — COMMENTED** [review]
If I recall correctly, discord.js doesn't allow just passing undefined for the intents. You have to actually give it an empty array instead. It'll scream at you about not passing the intents array otherwise

**Comment by dipamsen** [comment]
Fixed!

**Comment by shiffman** [comment]
Why do you think the discord.js guide includes this intent?

**Comment by dipamsen** [comment]
From discordjs.guide:

> The GatewayIntentBits.Guilds intents option is necessary for the discord.js client to work as you expect it to, as it ensures that the caches for guilds, channels, and roles are populated and available for internal use.

So looks like even if we don't actually listen to guild events, discord.js behind the scenes uses them to populate `client.guilds`, `client.guild.channels` etc. This is not used in the current example, but will be needed when working with guild stuff later.

**Comment by shiffman** [comment]
Thank you!

**Pull request merged**
