### PR TITLE
Update dotenv config import in bot.js

### PR DESCRIPTION
**Pull request by supercrafter100**
To address [this](https://github.com/Programming-from-A-to-Z/Discord-Bot-Examples/pull/13#issuecomment-1758920649) pr comment, I overlooked this file and originally assumed it was updated here too. Hence why it wasn't included in my original #13 pull request

### CODE REVIEW

**Comment by dipamsen** [comment]
I am thinking if we should instead use `dotenv.config()` everywhere (because that's what is shown in the video). Is there a preferred way to do this? (I don't think so)

**Comment by supercrafter100** [comment]
Usually destructuring is preferred for memory usage as you're only storing what you strictly want in the variable instead of the entirety of what dotenv exports.

**Comment by shiffman** [comment]
I don't mind if the video is slightly different, I can always add code comments here with further explanation. Feel free to help annotate if you like! Will merge for now. @supercrafter100 are you in the coding train discord?

**Comment by supercrafter100** [comment]
I am yeah. Username is the same as my GitHub name.

**Pull request merged**
